# Example Config File
log:
    filename: feedhandler.log
    level: WARNING

# Enable UVLoop (if not installed, will not cause errors)
uvloop: True

# Ignore invalid symbols/instruments
ignore_invalid_instruments: False

# Use multiprocessing for backends
backend_multiprocessing: False

# Secrets for exchanges
binance_futures:
    key_id: None
    key_secret: None
